/*

 SIMPELBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : D:\programmeren\cenasm\Gameboy\projecten\helloworldgameboy\src\env.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundtilesWidth 40
#define backgroundtilesHeight 18
#define backgroundtilesBank 0

extern unsigned char backgroundtiles[];

/* End of SIMPELBACKGROUND.H */
